export const languageOptions = [
  { value: "sq", label: "Albanian", flag: "https://flagcdn.com/24x18/al.png" },
  { value: "ar", label: "Arabic", flag: "https://flagcdn.com/24x18/sa.png" },
  { value: "bg", label: "Bulgarian", flag: "https://flagcdn.com/24x18/bg.png" },
  { value: "zh", label: "Chinese", flag: "https://flagcdn.com/24x18/cn.png" },
  { value: "cs", label: "Czech", flag: "https://flagcdn.com/24x18/cz.png" },
  { value: "da", label: "Danish", flag: "https://flagcdn.com/24x18/dk.png" },
  { value: "nl", label: "Dutch", flag: "https://flagcdn.com/24x18/nl.png" },
  { value: "fi", label: "Finnish", flag: "https://flagcdn.com/24x18/fi.png" },
  { value: "fr", label: "French", flag: "https://flagcdn.com/24x18/fr.png" },
  { value: "de", label: "German", flag: "https://flagcdn.com/24x18/de.png" },
  { value: "el", label: "Greek", flag: "https://flagcdn.com/24x18/gr.png" },
  { value: "hu", label: "Hungarian", flag: "https://flagcdn.com/24x18/hu.png" },
  { value: "is", label: "Icelandic", flag: "https://flagcdn.com/24x18/is.png" },
  { value: "it", label: "Italian", flag: "https://flagcdn.com/24x18/it.png" },
  { value: "ja", label: "Japanese", flag: "https://flagcdn.com/24x18/jp.png" },
  { value: "kk", label: "Kazakh", flag: "https://flagcdn.com/24x18/kz.png" },
  { value: "ko", label: "Korean", flag: "https://flagcdn.com/24x18/kr.png" },
  { value: "lv", label: "Latvian", flag: "https://flagcdn.com/24x18/lv.png" },
  {
    value: "lt",
    label: "Lithuanian",
    flag: "https://flagcdn.com/24x18/lt.png",
  },
  {
    value: "mk",
    label: "Macedonian",
    flag: "https://flagcdn.com/24x18/mk.png",
  },
  { value: "mn", label: "Mongolian", flag: "https://flagcdn.com/24x18/mn.png" },
  { value: "no", label: "Norwegian", flag: "https://flagcdn.com/24x18/no.png" },
  { value: "pl", label: "Polish", flag: "https://flagcdn.com/24x18/pl.png" },
  { value: "pt", label: "Portugese", flag: "https://flagcdn.com/24x18/pt.png" },
  { value: "ro", label: "Romanian", flag: "https://flagcdn.com/24x18/ro.png" },
  { value: "ru", label: "Russian", flag: "https://flagcdn.com/24x18/ru.png" },
  { value: "sr", label: "Serbian", flag: "https://flagcdn.com/24x18/rs.png" },
  { value: "sk", label: "Slovak", flag: "https://flagcdn.com/24x18/sk.png" },
  { value: "sl", label: "Slovenian", flag: "https://flagcdn.com/24x18/si.png" },
  { value: "es", label: "Spanish", flag: "https://flagcdn.com/24x18/es.png" },
  { value: "sv", label: "Swedish", flag: "https://flagcdn.com/24x18/se.png" },
  { value: "tr", label: "Turkish", flag: "https://flagcdn.com/24x18/tr.png" },
  { value: "uk", label: "Ukranian", flag: "https://flagcdn.com/24x18/ua.png" },
];
